- .gitignore
- Vagrantfile
- requirements.txt
This PR closes Issue #4. 
- Add `.gitignore` file
- Add `requirements.txt`
- Add `Vagrantfile`
> Add .gitignore Vagrantfile and requirements.txt

- .coveragerc
- Procfile
- config.py
- requirements.txt
- service/__init__.py
- service/model.py
- service/routes.py
- setup.cfg
- tests/test_models.py
- tests/test_routes.py
This PR closes #14. 
- Added `service` and `tests` starter code based on the template provided. 
- Certain lines were commented out to avoid errors while running
- Added other config files necessary
- Updated dependency `psycopg2-binary==2.8.6` to make it possible to run locally
- If running on VM, please use `flask run -h 0.0.0.0` to make the server visible
- Added dependency for `gunicorn` and `honcho`. 
- Added `Procfile` (start by running `honcho start`)
> Add-starter-code

- README.md
- Added a template for `READEME.md`
- We can add content to it as we implement more features, as specified in the User Story
> Add README template

- Vagrantfile
- config.py
- requirements.txt
- Updated `config.py` to use `PostgreSQL` by default
- Update `Vagrantfile` to reflect changes made in the template
- Updated `requirement.txt` to add dependencies for PostgreSQL
> Update DB URL to use PostgreSQL by default

- README.md
I added a description of Order model and Item model
> Update Readme with order API and DB Model

- Vagrantfile
- tests/test_model.py
- tests/test_routes.py
- updated the test modules to include setup and teardown methods consistent with the lab 
- updated vagrant file to add a test db
> update test modules to include setup and teardown methods

- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_orders.py
- tests/test_service.py
- added tests and functionality for updating orders 
- added attributes to the factory
> functionality and tests to update an order

- service/models.py
- service/routes.py
- tests/test_orders.py
- tests/test_service.py
Order Create
Item Create
Updated the test cases as per discussion
service/error_handlers.py      32     10    69%   27, 33-35, 57-59, 87-89
service/models.py              95      5    95%   129, 146, 163-165
service/routes.py              74      7    91%   121-127, 166
service/status.py              46      0   100%
TOTAL                         274     26    91%
> Item Creation

- service/models.py
- service/routes.py
- tests/test_orders.py
- tests/test_service.py
```
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
service/__init__.py            27      4    85%   45, 54-57
service/error_handlers.py      32     10    69%   27, 33-35, 57-59, 87-89
service/models.py             103      2    98%   166, 184
service/routes.py              79      0   100%
service/status.py              46      0   100%
---------------------------------------------------------
TOTAL                         287     16    94%
```
> Add delete methods for item

- service/models.py
- service/routes.py
- tests/test_orders.py
- tests/test_service.py
Resolves #9 
```
----------------------------------------------------------------------
XML: /vagrant/unittests.xml
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
service/__init__.py            27      4    85%   45, 54-57
service/error_handlers.py      32     10    69%   27, 33-35, 57-59, 87-89
service/models.py             111      1    99%   166
service/routes.py              93      1    99%   74
service/status.py              46      0   100%
---------------------------------------------------------
TOTAL                         309     16    95%
----------------------------------------------------------------------
Ran 23 tests in 0.929s
OK
```
> Query orders by customer_id and by including item

- service/models.py
- tests/test_orders.py
- tests/test_service.py
In this branch:
- add the route to LIST orders
- add test cases for LIST orders
Coverage:
```
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
service/__init__.py            27      4    85%   45, 54-57
service/error_handlers.py      32      3    91%   87-89
service/models.py             111      1    99%   174
service/routes.py              93      0   100%
service/status.py              46      0   100%
---------------------------------------------------------
TOTAL                         309      8    97%
```
> Add list orders

- .pylintrc
- README.md
- Vagrantfile
- service/__init__.py
- service/error_handlers.py
- service/models.py
- service/routes.py
- tests/factories.py
- tests/test_orders.py
- tests/test_service.py
Close #33
Refactor code to meet PEP8:
- `service`: 9.74/10
- `tests`: 9.78/10
> Code linting

- README.md
- Add codecov.io badge for code coverage
> Add Codecov.io badge

- config.py
- tests/test_orders.py
- tests/test_service.py
resolves #41
* update config.py to overwrite db url to elephant instance if the app is running on cloud
* update "test_orders.py" & "test_service.py" to take DATABASE_URL from config.py
> Get db url

- README.md
Configured the GitHub tool to our cloud toolchain. This tests to see if a pull request initiates the continuous delivery pipeline webhook.
> testing continuous delivery pipeline github webhook

- Vagrantfile
- features/environment.py
- features/orders.feature
- features/steps/orders_steps.py
- features/steps/web_steps.py
- requirements.txt
This PR introduces bdd. The following updates were made: 
* behave file structure 
* added bdd dependencies to requirements.txt 
* updated Vagrantfile to install chromium driver  
* test fixtures in environment.py
* sample data and load functionality 
* scenario and steps for testing the running server
> setup bdd 

- features/orders.feature
- features/steps/orders_steps.py
Update data loading functionality so that it works correctly when multiple scenarios are called in a bdd test suite. For each scenario the ```Background``` data in orders.feature file reloads. To account for this, I updated the orders step function to clear the context.order_ids list every time a new scenario is tested to avoid duplicating data entries.
> update load sample data functionality

- features/orders.feature
- features/steps/web_steps.py
* add scenario: update an order
* add some corresponding steps
> add update an order scenario and add corresponding steps

- features/environment.py
- features/orders.feature
- features/steps/items_steps.py
- features/steps/orders_steps.py
- features/steps/web_steps.py
- add scenario: Create a new Order in `orders.feature`
- add more helper functions in `web_steps.py`
> Add Scenario: Create a new Order

- features/orders.feature
Implemented BDD for Read an Order
> BDDforReadOrder

- .travis.yml
- add BDD script for Travis-CI
> Add BDD test job to travis-ci

- features/orders.feature
- service/static/js/rest_api.js
Here I update the bdd delete_scenario to use the latest search functionality. I also modified the search functionality to return "No orders found" message for queries with Customer ID that don't exist in the database
> modified delete scenario to use search functionality

- features/orders.feature
Implemented BDD for List Orders
> BDD for List

- Vagrantfile
- dot-env-example
- requirements.txt
- service/routes.py
The following changes: 
* update requirements 
* update routes.py file to use flask_restx
* define the Order model 
* provide a skeleton for several routes 
* Swagger docs now available at the /apidocs endpoint
> introduce restx and swagger docs

- service/routes.py
Please modify the `location_url` related code once `get` is implemented. Thank you!
> Refactor Create

- service/routes.py
This reverts commit e14499ab85b75900d11edcbbd7e73926730e7ea9.
> Revert "Refactor Create (#106)"

- features/steps/orders_steps.py
- service/routes.py
- tests/test_service.py
Completed during a Peer programming session. Contributors are @luke0zong, @pkutlesa, and @OliverZWang. 
- Refactor `Get`
- Updated model. 
- Fixed bug in behavior testing code
- Fixed `500` error when creating without `customer_id`
> Restx get fix 500

- service/routes.py
- service/static/js/rest_api.js
- tests/test_service.py
* refactor cancel route using restx
* change cancel route from POST to PUT method 
* update cancel button and tests to use put requests to the cancel route
> refactor cancel route

- service/routes.py
Added integration test stage to our delivery service toolchain. This pr is used to trigger the pipeline and showcase a working test stage.
> push to trigger delivery pipeline

- service/error_handlers.py
- service/routes.py
- refactor update route using restx
- remove 405 error in error handler
> Refactor update route

- service/routes.py
Restarted ElephantSQL connection
> commit used to trigger and test delivery pipeline

- service/routes.py
* Refactor List and Query
* Add Swagger doc for List and Query
> Refactor list

- service/routes.py
* Avoid using multiple location in reqparse
> Fix swagger.json Fetch error

- service/routes.py
* refactor get item
* refactor create an item
* fix a small typo bug
* modified 'id' into 'item_id'
* this bug will disorder the key name in response body
* which will cause key error in TDD tests
> refactor get item and create an item

- service/routes.py
Thanks to @JoanneWooW for helping debug this route!
> Refactor delete item using restx
